### ISSUE TITLE
Multiple volume support

### ISSUE THREAD

**Issue by craig-willis** [nds-org/ndslabs#13]
Currently, services can only have one volume. We need to figure out how best to handle services with multiple volumes -- or whether this is really a good requirement.

**Comment by bodom0015** [comment]
We might also discuss the potential for sharing data between volumes. ownCloud / Clowder are potential examples of where this might come in handy, as they work as file upload services that do not enforce a particular data format.

NOTE: This may not make sense for pre-formatted data (i.e. you can't simply connect a MongoDB volume to MySQL and expect it to work without some manual steps).

**Comment by bodom0015** [comment]
Multiple volumes per-service are now supported on master.
