### ISSUE TITLE
Dependency shutdown(/startup) ordering

### ISSUE THREAD

**Issue by craig-willis** [nds-org/ndslabs#14]
There's currently no way to specify dependency shutdown order.  There are cases where shutdown order matters, such as RabbitMQ and extractors. Shutting down rabbit before extractors causes extractor error during shutdown.

**Comment by bodom0015** [comment]
Related to issue #16

**Comment by craig-willis** [comment]
The original problem was that starting up or shutting down Clowder with the PlantCV extractor resulted in errors.  I've implemented a change to the API Server to shutdown services based in the reverse order they were started -- services with dependencies are shutdown first and dependent services are not shutdown until the dependee is shutdown. Related to #16, services are shutdown in parallel when possible.   To test this, you should be able to start Clowder with all optional services and shutdown. You should see multiple services enter the "waiting" state at the same time.  

Unfortunately, this doesn't full resolve the PlantCV/Rabbit problem on startup. I had to make a spec change to add a readyProbe on RabbitMQ with a 20 second wait, otherwise it still ended up in error during startup.

**Comment by craig-willis** [comment]
Changes available in ndslabs/apiserver:test

**Comment by bodom0015** [comment]
This should now be fixed on master.
