### ISSUE TITLE
Parallel startup/shutdown for independent services

### ISSUE THREAD

**Issue by craig-willis** [nds-org/ndslabs#16]
There's no need to start services sequentially if they have no dependencies. Speed up startup and shutdown times by starting/stopping independent services in parallel.

**Comment by bodom0015** [comment]
For stopping a running stack, it should be possible to shut down all running services simultaneously. This has worked well in the past for our stop scripts, but may need further investigation in case there are any quirks / edge cases that may result from doing this within NDS Labs.

**Comment by bodom0015** [comment]
One way to handle this case might be to provide a mapping of which services can be started together:

For example:
```js
"phases": [
  [ "mongo", "rabbitmq" ],
  [ "clowder" ],
  [ "plantcv", "image-preview", "video-preview" ]
]
```

In the above example, mongo and rabbit can be started together, but Clowder must be started after both. The extractors can then all be started simultaneously after Clowder/RabbitMQ have started.

I am less familiar with the Dataverse dependency startup/shutdown order, so this paradigm may not fit that case.

Alternatives:
If "phases" needs to be keyed by something other than index, we could make that an object.
If we need different fields, we could make the "value" of "phases" an object instead of just an array.

**Comment by craig-willis** [comment]
Another option might be to remove the startup/shutdown dependency altogether, and require that the services (via entrypoint or similar) wait for dependencies to become available or wait to shutdown. This way, the burden is on the individual services to know what they need and when.

**Comment by bodom0015** [comment]
Some concerns that I have with this approach:
1. we may lose reusability for services that are tied to multiple stacks
2. service entrypoint scripts may become unwieldy if they are tied to too many services
3. additional modifications may be required for any official images that we plan to use
4. this puts the work of integration on the developer attempting to integrate services in NDS Labs (which may be a good thing or a bad thing)
5. discovering stack-related services at the Docker/entrypoint level seems challenging

Perhaps I am overthinking/misunderstanding your approach, but if you want to walk through a test case to show me what you mean in more detail, I would certainly be open to that.

**Comment by craig-willis** [comment]
See comment in issue #14.  This has been resolved by starting and stoping services in parallel when possible.  Dependencies must always start first and be stopped last, but if a service has no dependencies or all dependencies are in the right state, they are started.

The easiest way to test this is to start/stop Clowder with the full set of optional services. Mongo, Rabbit and Elastic can start in parallel.  The extractors must wait for Rabbit to be ready, but can start in parallel.  Clowder, due to dependency on extractors, starts a lonely last.

**Comment by craig-willis** [comment]
Changes available in ndslabs/apiserver:test

**Comment by bodom0015** [comment]
This should now be fixed on master.
