### ISSUE TITLE
Orphaned volumes add to 'Projected Usage'

### ISSUE THREAD

**Issue by bodom0015** [nds-org/ndslabs#24]
Currently, the UI gives the option to reuse existing (detached) volumes that the user has already allocated for a particular service. Even though these volumes have already been allocated, they are still reflected as contributing to the 'Projected Usage' in the volumes page of the configuration wizard.

This is clearly a mistake, and needs to be addressed as we flesh out more of the strategy for enforcing storage quotas in NDS Labs.

**Comment by bodom0015** [comment]
As a part of this issue, I will also attempt to ensure that the storage quota (placeholder) is uniform throughout.

There are some places that still reference the old placeholder value of "50 GB", when the new placeholder should be ~10 GB.

**Comment by craig-willis** [comment]
Confirmed fixed in build gh-issue-24
