### ISSUE TITLE
Refresh token on wizard page navigation

### ISSUE THREAD

**Issue by bodom0015** [nds-org/ndslabs#26]
The current timeout for an auth token is 30 minutes. In extreme cases, this timeout can occur during the configuration of a stack. This will bounce the user to the login page without creating their stack, and force them to reconfigure it using the wizard.

To combat this problem, the wizard should refresh the user's token whenever they change between each discrete step of the wizard.

**Comment by craig-willis** [comment]
Confirmed working in build NDS-170
