### ISSUE TITLE
Support more fine-grained security capabilities

### ISSUE THREAD

**Issue by bodom0015** [nds-org/ndslabs#266]
As an administrator of Workbench, it would be nice to be able to define more fine-grained security permissions for each service. The API currently allows us to specify "privileged", even if the UI does not offer this option directly. It would be nice to be able to specify particular permissions, instead of giving full root access with `privileged`.

It may be as simple as tracking down anywhere that `privileged` is specified and replacing it with a "securityContext" block (to share the exact syntax with the Kubernetes spec) defining zero or more permissions. We would need to replace this in each spec, as well as adjusting the handling for this field in the API server.

See [Security Context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/) for more details

This task is complete when:
* ndslabs-specs has been updated where necessary to tune down the allowed permissions of privileged specs
* ndslabs has been updated to handle the new `securityContext` block appropriately and to copy these capabilities into the user's stack service container(s)

**Comment by bodom0015** [comment]
References to `privileged` that should be expanded from `boolean` to object:
- Spec type definition where spec is first defined (types.go:29)
- PostService where spec is added to user catalog (server.go:1148)
- PutService where spec is updated in user catalog (server.go:1226)
- CreateControllerTemplate where spec is parsed into an RC (kube.go:575)

**Comment by craig-willis** [comment]
Merged the API server changes, but we still need to modify the existing specs?

**Comment by bodom0015** [comment]
https://github.com/cheese-hub/catalog/pull/9 has been merged
