### ISSUE TITLE
Shared data should be configurable

### ISSUE THREAD

**Issue by craig-willis** [nds-org/ndslabs#268]
With https://github.com/nds-org/ndslabs/pull/261 merged, we have an open question about how to handle shared data.  Today, it's assumed to be an NFS mount via hostpath (ala TERRA-REF use case), but really should be an NFS RWM mount (not hostpath).

**Comment by bodom0015** [comment]
There are still unresolved issues here, namely that PVCs are namespaces objects.

We may be unable to rely on PVCs to solve this problem, and may need to go with a raw NFS mount to the pods

Related design notes:
https://opensource.ncsa.illinois.edu/confluence/display/NDS/Rethinking+Shared+Storage

**Comment by bodom0015** [comment]
This is included in V2
