### ISSUE TITLE
Explore spec validation

### ISSUE THREAD

**Issue by bodom0015** [nds-org/ndslabs#29]
The only way we can currently test that a spec works is by configuring it and running a stack. This is tedious when attempting to rapidly test changes to a spec.

We should investigate whether it would be possible / useful to attempt to validate the spec when adding it to the service list, rather than attempting to do it when the user runs an instance of the stack described by the spec.

**Comment by craig-willis** [comment]
https://opensource.ncsa.illinois.edu/jira/browse/NDS-373
